version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "8050:8050"
    networks:
      - calendar-network
    links:
      - data
    depends_on:
      - data
    volumes:
      - ./logs:/logs
  data:
    image: postgres:14.54
    environment:
      POSTGRES_DB: "calendardb"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
      PGDATA: "./db/data"
    volumes:
      - ./data/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U usr -d pwd" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
networks:
  calendar-network:
    driver: bridge