CREATE TYPE EVENT_REPEAT_TYPE IF NOT EXISTS AS ENUM (
    'SINGLE_MEETING',
    'REPEAT_DAILY',
    'REPEAT_WEEKLY',
    'REPEAT_MONTHLY',
    'REPEAT_YEARLY',
    'REPEAT_WORKDAYS',
    'REPEAT_CUSTOM',
    );

CREATE TABLE IF NOT EXISTS events (
   id TEXT PRIMARY KEY,
   creator TEXT NOT NULL,
   start_time TIMESTAMP WITH TIME ZONE NOT NULL,
   duration INTERVAL NOT NULL,
   is_private BOOLEAN NOT NULL,
   schedule_type EVENT_REPEAT_TYPE NOT NULL,
   description TEXT NOT NULL
);
